kubectl apply -f- <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moesif-exproc-plugin
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      app: moesif-exproc-plugin
  replicas: 1
  template:
    metadata:
      labels:
        app: moesif-exproc-plugin
    spec:
      containers:
        - name: moesif-exproc-plugin
          image: mcallisterpetr/simple-rust-app:0.2.14
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: MOESIF_APPLICATION_ID
              value: "eyJhcHAiOiI0OTM6MTI4NiIsInZlciI6IjIuMSIsIm9yZyI6IjU3Mzo1NzAiLCJpYXQiOjE3MjI0NzA0MDB9.Bg4CIwiKtLgcv0vfNK-B6ztAe2KuYRM7ThIAaDz1D9I"
            - name: USER_ID_HEADER
              value: "X-User-Example-Header"  
            - name: COMPANY_ID_HEADER
              value: "X-Company-Example-Header"  
            - name: UPSTREAM
              value: "outbound|443||api.moesif.net" 
            - name: DEBUG
              value: "true" 
            - name: RUST_LOG
              value: debug

---
apiVersion: v1
kind: Service
metadata:
  name: moesif-exproc-plugin
  namespace: gloo-system
  labels:
    app: moesif-exproc-plugin
  annotations:
    gloo.solo.io/h2_service: "true"
spec:
  ports:
  - port: 4445
    targetPort: 50051
    protocol: TCP
  selector:
    app: moesif-exproc-plugin
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    app: moesif-exproc-plugin
    discovered_by: kubernetesplugin
  name: moesif-exproc-plugin
  namespace: gloo-system
spec:
  discoveryMetadata: {}
  useHttp2: true
  kube:
    selector:
      app: moesif-exproc-plugin
    serviceName: moesif-exproc-plugin
    serviceNamespace: gloo-system
    servicePort: 4445
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: moesif-exproc-plugin
  namespace: httpbin
spec:
  parentRefs:
    - name: http
      namespace: gloo-system
  hostnames:
    - "moesif.example.com"
  rules:
    - backendRefs:
        - name: httpbin
          port: 8000
EOF
